Sorry: TabError: inconsistent use of tabs and spaces in indentation (depth_robot_walking.py, line 29)
